# Generated by Django 4.2.7 on 2024-05-02 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('verification_token', models.CharField(blank=True, max_length=100, null=True)),
                ('email_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='nombre',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='publicacion',
            old_name='texto',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='ubicacion',
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='perfil_privado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.usuario'),
        ),
    ]
