# Generated by Django 4.2.7 on 2024-05-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_usuario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='aka',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='pics_profile/'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='imagenes',
            field=models.ImageField(default='pics_profile/default.png', upload_to='imagenes_publicacion/'),
        ),
    ]
