# Generated by Django 4.2.7 on 2024-05-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_perfilusuario_aka_alter_perfilusuario_foto_perfil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='fotos-publicaciones/')),
            ],
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='pics_profile/default.png', null=True, upload_to='pics_profile/'),
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='imagenes',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='imagenes',
            field=models.ManyToManyField(null=True, related_name='publicaciones', to='blog.imagen'),
        ),
    ]
