# Generated by Django 4.2.7 on 2024-05-30 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_comentario_texto_alter_publicacion_etiquetas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('l', 'Like'), ('f', 'Follow'), ('c', 'Comment')], max_length=2)),
                ('perfil_emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emisor', to='blog.perfilusuario')),
                ('perfil_receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptor', to='blog.perfilusuario')),
            ],
        ),
    ]
