# Generated by Django 4.2.7 on 2024-05-30 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_grupo_administrador_remove_grupo_miembros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='publicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publicacion', to='blog.publicacion'),
        ),
    ]
