# Generated by Django 4.2.7 on 2024-06-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_notificacion_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='vista',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='action',
            field=models.CharField(choices=[('l', 'Like'), ('f', 'Follow')], max_length=2),
        ),
    ]
