FROM node:16

WORKDIR /app

COPY spotpeeker-front/spotpeeker/package.json spotpeeker-front/spotpeeker/package-lock.json* ./

RUN npm install

RUN npm install react-router-dom

COPY ./spotpeeker-front/spotpeeker .

EXPOSE 5173

CMD ["npm", "run", "dev"]
